module.exports = {
  apiUri: 'https://skills-matrix-cafedavid.c9users.io/api',
  displayApp: 'Skills Matrix',
  displayCapabilities: 'Capabilities',
  displayCapability: 'Capability',
  displaycapabilities: 'capabilities',
  displaycapability: 'capability',
  displayEmployee: 'Employee',
  displayEmployees: 'Employees',
  displayemployee: 'employee',
  displayemployees: 'employees',
  displayOrganization: 'Organization',
  displayOrganizations: 'Organizations',
  displayorganization: 'organization',
  displayorganizations: 'organizations',
  displaySkill: 'Skill',
  displaySkills: 'Skills',
  displayskill: 'skill',
  displayskills: 'skills',
  displayStrategies: 'Strategies',
  displaystrategies: 'strategies',
  displayStrategy: 'Strategy',
  displaystrategy: 'strategy',
  displayVisibility: 'Visbility',
  domain: 'skills-matrix-cafedavid.c9users.io',
  hotModuleReloadUri: 'skills-matrix-cafedavid.c9users.io',
  mongoUri: 'mongodb://localhost:27017/skills-matrix',
  port: process.env.PORT,
  protocol: 'https',
  serverCertificate: '',
  serverCertificateAuthority: '',
  serverKey: '',
  sessionSecret: 'SECRETS',
  // N + 1 CAN SEE EVERYTHING, ORDER MATTERS
  visibility: [
    'Employee',
    'Manager',
    'Vice President',
    'Executive'
  ]
}